# Generated by Django 5.0 on 2023-12-18 05:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookFile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='books', verbose_name='Файл с книгой'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Художественная литература'), (1, 'Научная литература')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photoPreview',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cover', validators=[api.models.Book.validate_image], verbose_name='Изображения'),
        ),
    ]
